name = "Pol"
uuid = "4d414b72-cacd-4c1f-bb87-6585853948d5"
version = "0.1.0"
authors = ["AntonOresten <antonoresten@proton.me> and contributors"]

[workspace]
projects = ["test", "docs"]

[deps]
Republic = "27243419-9dde-4721-b67c-fd63626fea7f"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"

[weakdeps]
CUDACore = "bd0ed864-bdfe-4181-a5ed-ce625a5fdea2"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"

[extensions]
CUDACoreExt = ["CUDACore"]
GPUArraysExt = ["GPUArrays"]

[compat]
CUDACore = "6"
GPUArrays = "11"
Republic = "2"
ScopedValues = "1.6.2"
julia = "1.10"
